### ISSUE TITLE
Error on ejecuting npm run dev

### ISSUE THREAD

**Issue by gabrieljaime** [acacha/adminlte-laravel#287]
Hi, im instal a fresh laravel installation and then i install the package, but when i want to run 
`npm run dev`

i have an error:

```
 cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

C:\xampp\htdocs\pm\webpack.mix.js:43
if (mix.config.inProduction) {
              ^
TypeError: Cannot read property 'inProduction' of undefined
    at Object.<anonymous> (C:\xampp\htdocs\pm\webpack.mix.js:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\pm\node_modules\laravel-mix\setup\webpack.config.js:9:1)
    at Module._compile (module.js:570:32)
```

and obviously i can't find the way to fix it

> Node Version : 6.11.0
> Npm Version: 5.0.3
> Laravel Version: 5.4.27

Thank for you help...

**Comment by timo002** [comment]
Same issue here!

**Comment by acacha** [comment]
Yes npm install is mandatory as usual in these kinds of projectes
